---
title: "Bench Depth Analysis"
output: html_notebook
---

```{r}
install.packages("rvest")
library(rvest)
install.packages("dplyr")
library(dplyr)
install.packages("polite")
library(polite)
installe.packages("janitor")
library(janitor)
install.packages("tidyr")
library(tidyr)
```

```{r}
#acc_page2526 <- read_html("/Users/hanabaskin/Desktop/2025-26 Men's Atlantic Coast Conference Player Stats _ College Basketball at Sports-Reference.com.html")
```

```{r}
session <- bow(
  "https://www.sports-reference.com/cbb/conferences/acc/men/2026-stats.html",
  user_agent = "Mozilla/5.0",
  delay = 10  # Wait 10 seconds between requests
  )

# Scrape the page
acc_page2526 <- scrape(session)
```

```{r}
acc_basketball_confstats_2526 <- acc_page2526 |>
  html_element("#players_per_game_conf") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/duke/men/2026.html#all_roster",
#   user_agent = "Mozilla/5.0",
#   delay = 10  
#   )
# 
# duke_page <- scrape(session)

duke_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Duke Blue Devils Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

duke_roster <- duke_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/north-carolina/men/2026.html#all_roster",
#    user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# unc_page <- scrape(session)

unc_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 UNC Tar Heels Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

unc_roster <- unc_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/pittsburgh/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# pitt_page <- scrape(session)

pitt_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Pitt Panthers Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")
  
pitt_roster <- pitt_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/syracuse/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# syr_page <- scrape(session)

syr_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Syracuse Orange Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

syr_roster <- syr_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/georgia-tech/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# gt_page <- scrape(session)

gt_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Georgia Tech Yellow Jackets Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

gt_roster <- gt_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/virginia-tech/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# vt_page <- scrape(session)

vt_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Virginia Tech Hokies Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

vt_roster <- vt_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/virginia/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
#                
# uva_page <- scrape(session)

uva_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Virginia Cavaliers Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

uva_roster <- uva_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/boston-college/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# bc_page <- scrape(session)

bc_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Boston College Eagles Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

bc_roster <- bc_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/california/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# cal_page <- scrape(session)

cal_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 California Golden Bears Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

cal_roster <- cal_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/clemson/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# clemson_page <- scrape(session)

clemson_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Clemson Tigers Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

clemson_roster <- clemson_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/florida-state/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# fsu_page <- scrape(session)

fsu_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Florida State Seminoles Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

fsu_roster <- fsu_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/louisville/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# louisville_page <- scrape(session)

louisville_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters//2025-26 Louisville Cardinals Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

louisville_roster <- louisville_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/miami-fl/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# miami_page <- scrape(session)

miami_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Miami (FL) Hurricanes Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

miami_roster <- miami_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/north-carolina-state/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# ncstate_page <- scrape(session)

ncstate_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 NC State Wolfpack Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

ncstate_roster <-ncstate_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/notre-dame/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# nd_page <- scrape(session)

nd_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Notre Dame Fighting Irish Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

nd_roster <-nd_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/southern-methodist/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# smu_page <- scrape(session)

smu_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 SMU Mustangs Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

smu_roster <-smu_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/stanford/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# stanford_page <- scrape(session)

stanford_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Stanford Cardinal Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

stanford_roster <-stanford_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
# session <- bow(
#   "https://www.sports-reference.com/cbb/schools/wake-forest/men/2026.html",
#   user_agent = "Mozilla/5.0",
#   delay = 10
#   )
# 
# wake_page <- scrape(session)

wake_page <- read_html("/Users/hanabaskin/Desktop/Basketball Analysis/25-26 Team Rosters/2025-26 Wake Forest Demon Deacons Men's Roster and Stats _ College Basketball at Sports-Reference.com.html")

wake_roster <-wake_page |>
  html_element("#roster") |>
  html_table() |>
  clean_names()
```

```{r}
acc_rosters <- bind_rows(
  duke_roster,
  unc_roster,
  uva_roster,
  wake_roster,
  ncstate_roster,
  stanford_roster,
  nd_roster,
  vt_roster,
  syr_roster,
  pitt_roster,
  smu_roster,
  miami_roster,
  louisville_roster,
  gt_roster,
  fsu_roster,
  clemson_roster,
  cal_roster,
  bc_roster
)
```

```{r}
library(stringr)

clean_player_name <- function(x) {
  x |>
    str_replace_all("’", "'") |>                 # normalize apostrophes
    str_remove_all("\\s(Jr\\.|Sr\\.|II|III|IV|V)$") |>  # remove suffixes
    str_squish()
}
```

```{r}
#clean the names in the stats table and rosters table

acc_basketball_confstats_2526 <- acc_basketball_confstats_2526 |>
  mutate(player = clean_player_name(player))

acc_rosters <- acc_rosters |>
  mutate(player = clean_player_name(player))

#join stats and rosters so that every player also has their class listed

acc_stats_byclass <- acc_basketball_confstats_2526 |>
  left_join(
    acc_rosters,
    by = "player"
  )
```

```{r}
acc_stats_byclass <- acc_stats_byclass |>
  mutate(
    experience_group = case_when(
      class %in% c("FR", "SO") ~ "Underclassmen",
      class %in% c("JR", "SR", "GR") ~ "Upperclassmen"
    )
  )
```

```{r}
transfer_list <- read.csv("/Users/hanabaskin/Desktop/Basketball Analysis/ACC Transfers 25 - Sheet1.csv")

acc_rosters <- acc_rosters |>
  left_join(
    transfer_list, 
    by = "player"
  )

acc_stats_byclass <- acc_stats_byclass |>
  left_join(
    acc_rosters |>
      select(player, transfer_from),
    by = "player"
  )
```

```{r}
minutes_concentration <- acc_stats_byclass |>
  group_by(team) |>
  mutate(
    total_mp = mp * g,  # Convert per game mp to total minutes played
    total_team_minutes = sum(total_mp)
  ) |>
  arrange(team, desc(mp)) |>  # sort descending so players with more minutes are at the top
  mutate(player_rank = row_number()) |> # rank players based on where the fall in the list (players with more minutes first)
  group_by(team) |>
  summarise(
    total_team_minutes = first(total_team_minutes),
    top5_minutes_pct = sum(total_mp[player_rank <= 5]) / total_team_minutes * 100, # percentage of minutes played by top 5 players
    top7_minutes_pct = sum(total_mp[player_rank <= 7]) / total_team_minutes * 100,
    top8_minutes_pct = sum(total_mp[player_rank <= 8]) / total_team_minutes * 100
  )|>
  drop_na()

```

```{r}
# counting the number of players in each minutes played group

rotation_size <- acc_stats_byclass |>
  group_by(team) |>
  summarise(
    players_10plus_mp = sum(mp >= 10), # number of players who get 10 or more minutes per game
    players_15plus_mp = sum(mp >= 15),
    players_20plus_mp = sum(mp >= 20)
  ) |>
  drop_na()
```

```{r}
scoring_efficiency_depth <- acc_stats_byclass |>
  mutate(points_per_minute = pts / mp) |> # calculating score efficiency as points per minutes played
  arrange(team, desc(mp)) |>
  group_by(team) |>
  mutate(player_rank = row_number()) |> # rank each player by how many points per minute they score
  group_by(team) |>
  summarise(
    top5_ppm = mean(points_per_minute[player_rank <= 5], na.rm = TRUE), # average points per minute by 5 starters
    bench_ppm = mean(points_per_minute[player_rank > 5], na.rm = TRUE), #average points per minute outside of 5 starters
    bench_efficiency_ratio = bench_ppm / top5_ppm # higher values means more points coming from bench
  ) |>
  drop_na() |>
  arrange(desc(bench_efficiency_ratio))
```

```{r}
depth_analysis <- minutes_concentration |>
  left_join(rotation_size, by = "team") |>
  left_join(scoring_efficiency_depth, by = "team") |>
  arrange(desc(bench_efficiency_ratio))
```

```{r}
library(ggplot2)
install.packages("ggimage")
library(ggimage)
```

```{r}
depth_analysis <- depth_analysis |>
  mutate(
    logo = case_when(
      team == "Duke" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/duke_logo.webp",
      team == "North Carolina" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/unc_logo.webp",
      team == "Virginia" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/uva_logo.webp",
      team == "Notre Dame" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/nd_logo.webp",
      team == "Virginia Tech" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/vt_logo.webp",
      team == "Stanford" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/stanford_logo.webp",
      team == "SMU" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/smu_logo.webp",
      team == "Boston College" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/bc_logo.webp",
      team == "Clemson" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/clemson_logo.webp",
      team == "Pittsburgh" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/pitt_logo.webp",
      team == "Syracuse" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/syr_logo.webp",
      team == "Miami (FL)" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/miami_logo.webp",
      team == "Georgia Tech" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/gt_logo.webp",
      team == "NC State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/ncstate_logo.webp",
      team == "Florida State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/fsu_logo.webp",
      team == "Louisville" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/louisville_logo.webp",
      team == "Wake Forest" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/wake_logo.webp",
      team == "California" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/cal_logo.webp",
    )
  )
```

```{r}
mean_top5_minutes_pct <- depth_analysis |>
  summarise(m = mean(top5_minutes_pct)) |>
  pull(m)
```
```{r}
mean_bench_efficiency_ratio <- depth_analysis |>
  summarise(m = mean(bench_efficiency_ratio)) |>
  pull(m)
```

```{r}
depth_analysis |>
  ggplot(aes(x = top5_minutes_pct, y = bench_efficiency_ratio)) +
  geom_image(aes(image = logo), size = 0.05) +
  labs(
    title = "ACC Bench Depth Analysis",
    subtitle = "Minutes Concentration vs. Bench Production",
    x = "% of Minutes to Top 5 Players",
    y = "Bench Efficiency Ratio (Bench PPM / Top 5 PPM)",
    caption = "Data: ACC Conference Play 2025-26"
  ) +
  geom_hline(yintercept = mean_bench_efficiency_ratio, linetype = "dashed", color = "red", alpha = 0.5) +
  geom_vline(xintercept = mean_top5_minutes_pct, linetype = "dashed", color = "red", alpha = 0.5) +
  theme_minimal()
```

```{r}
ggsave("bench_depth_plot.png")
```
```{r}
# A starter is anyone who started in at least once conference game

starters <- read.csv("/Users/hanabaskin/Desktop/Basketball Analysis/Starters - Sheet1.csv")
```

```{r}
starters_lookup <- starters |>
  distinct(team, player) |>
  mutate(role = "Starter")
```

```{r}
# Assigns everyone as a starter or bench player

acc_stats_with_role <- acc_stats_byclass |>
  left_join(
    starters_lookup,
    by = c("team", "player")
  ) |>
  mutate(
    role = if_else(is.na(role), "Bench", role)
  )
```

```{r}
# Check to see how many starters vs bench players on each team
acc_stats_with_role |>
  distinct(team, player, role) |>
  count(team, role)
```
```{r}
bench_vs_starters <- acc_stats_with_role |>
  mutate(total_minutes = mp * g) |>
  group_by(team, role) |>
  summarise(
    minutes = sum(total_minutes),
    points = sum(pts),
    ppm = points / minutes,
    .groups = "drop"
  ) |>
  pivot_wider(
    names_from = role,
    values_from = c(minutes, points, ppm)
  ) |>
  drop_na()
```

```{r}
bench_vs_starters_analysis <- bench_vs_starters |>
  mutate(
    minutes_team = minutes_Starter + minutes_Bench,
    pct_minutes_starters = minutes_Starter / minutes_team * 100,
    pct_minutes_bench    = minutes_Bench / minutes_team * 100,
    bench_efficiency_ratio = ppm_Bench / ppm_Starter
  ) |>
  select(team, minutes_team, pct_minutes_starters, ppm_Starter, pct_minutes_bench, ppm_Bench, bench_efficiency_ratio) |>
  arrange(desc(bench_efficiency_ratio))
```

```{r}
mean_starters_minutes_pct <- bench_vs_starters_analysis |>
  summarise(m = mean(pct_minutes_starters)) |>
  pull(m)
```
```{r}
mean_bench_efficiency_ratio <- bench_vs_starters_analysis |>
  summarise(m = mean(bench_efficiency_ratio)) |>
  pull(m)
```

```{r}
bench_vs_starters_analysis <- bench_vs_starters_analysis |>
  mutate(
    logo = case_when(
      team == "Duke" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/duke_logo.webp",
      team == "North Carolina" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/unc_logo.webp",
      team == "Virginia" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/uva_logo.webp",
      team == "Notre Dame" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/nd_logo.webp",
      team == "Virginia Tech" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/vt_logo.webp",
      team == "Stanford" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/stanford_logo.webp",
      team == "SMU" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/smu_logo.webp",
      team == "Boston College" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/bc_logo.webp",
      team == "Clemson" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/clemson_logo.webp",
      team == "Pittsburgh" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/pitt_logo.webp",
      team == "Syracuse" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/syr_logo.webp",
      team == "Miami (FL)" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/miami_logo.webp",
      team == "Georgia Tech" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/gt_logo.webp",
      team == "NC State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/ncstate_logo.webp",
      team == "Florida State" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/fsu_logo.webp",
      team == "Louisville" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/louisville_logo.webp",
      team == "Wake Forest" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/wake_logo.webp",
      team == "California" ~ "/Users/hanabaskin/Desktop/Basketball Analysis/Team Logos/cal_logo.webp",
    )
  )
```

```{r}
bench_vs_starters_analysis |>
  ggplot(aes(x = pct_minutes_starters, y = bench_efficiency_ratio)) +
  geom_image(aes(image = logo), size = 0.05) +
  labs(
    title = "ACC Bench Depth Analysis",
    subtitle = "Minutes Concentration vs. Bench Production",
    x = "% of Minutes to Starters",
    y = "Bench Efficiency Ratio (Bench PPM / Starters PPM)",
    caption = "Data: ACC Conference Play 2025-26"
  ) +
  geom_hline(yintercept = mean_bench_efficiency_ratio, linetype = "dashed", color = "red", alpha = 0.5) +
  geom_vline(xintercept = mean_starters_minutes_pct, linetype = "dashed", color = "red", alpha = 0.5) +
  theme_minimal()
```
```{r}
ggsave("bench_depth_starters_plot.png")
```

