---
title: "R Notebook"
output: html_notebook
---
```{r}
# # import cbbpy.mens_scraper as ms
# # import pandas as pd
# # import os
# # 
# game_ids = [
#     "401820648",
#     "401820661",
#     "401820672",
#     "401820675",
#     "401820687",
#     "401820697",
#     "401820639",
#     "401820634",
#     "401820637",
#     "401820635",
#     "401820636",
#     "401820641",
#     "401820638",
#     "401820640",
#     "401820643",
#     "401820642",
#     "401820644",
#     "401820646",
#     "401820649",
#     "401820647",
#     "401820645",
#     "401820650",
#     "401820653",
#     "401820651",
#     "401820654",
#     "401820652",
#     "401820656",
#     "401820655",
#     "401820657",
#     "401820659",
#     "401820664",
#     "401820660",
#     "401820658",
#     "401820663",
#     "401820665",
#     "401820662",
#     "401820669",
#     "401820667",
#     "401820670",
#     "401820673",
#     "401820666",
#     "401820668",
#     "401820671",
#     "401820681",
#     "401820680",
#     "401820679",
#     "401820676",
#     "401820682",
#     "401820678",
#     "401820674",
#     "401820677",
#     "401820685",
#     "401820686",
#     "401820683",
#     "401820684",
#     "401820688",
#     "401820689",
#     "401820690",
#     "401820691",
#     "401820693",
#     "401820696",
#     "401820694",
#     "401820692",
#     "401820695"
# ]
# # 
# # # folder to save CSVs
# # output_folder = "pbp_csvs"
# # os.makedirs(output_folder, exist_ok=True)
# # 
# # for gid in game_ids:
# #     try:
# #         pbp = ms.get_game_pbp(gid)
# #         pbp.reset_index(drop=True, inplace=True)
# #         csv_path = os.path.join(output_folder, f"{gid}_pbp.csv")
# #         pbp.to_csv(csv_path, index=False)
# #         print(f"Saved {gid}")
# #     except Exception as e:
# #         print(f"Error with game {gid}: {e}")
# 
# !zip -r /content/pbp_csvs.zip /content/pbp_csvs
```
```{r}

```

```{r}
folder <- "/Users/hanabaskin/Desktop/Basketball Analysis/pbp_csvs_25_26"

csv_files <- list.files(folder, pattern = "*.csv", full.names = TRUE)

all_games <- lapply(csv_files, read_csv) |> bind_rows()
```

```{r}
head(all_games)
```

```{r}
# Calculating score margin and flag for close games as 5 points or less

all_games <- all_games |>
  mutate(
    margin = home_score - away_score,
    close_game = abs(margin) <= 5 
  )
```

```{r}
unique(all_games$play_type)
```

```{r}
# Timeouts when game is close

timeouts_close <- all_games |>
  filter(play_type == "timeout" & close_game)
```

```{r}
# Fouls when game is close

fouls_close <- all_games |>
  filter(play_type == "foul" & close_game)
```

```{r}
# Cleaning play_team variable to remove mascot

pbp <- all_games |>
  mutate(
    home_team = case_when(
      str_detect(home_team, "Virginia Tech") ~ "Virginia Tech",
      str_detect(home_team, "North Carolina") ~ "North Carolina",
      str_detect(home_team, "Notre Dame") ~ "Notre Dame",
      str_detect(home_team, "Boston College") ~ "Boston College",
      str_detect(home_team, "California") ~ "California",
      str_detect(home_team, "Clemson") ~ "Clemson",
      str_detect(home_team, "Duke") ~ "Duke",
      str_detect(home_team, "Florida State") ~ "Florida State",
      str_detect(home_team, "Georgia Tech") ~ "Georgia Tech",
      str_detect(home_team, "Louisville") ~ "Louisville",
      str_detect(home_team, "Miami") ~ "Miami (FL)",
      str_detect(home_team, "NC State") ~ "NC State",
      str_detect(home_team, "Pittsburgh") ~ "Pittsburgh",
      str_detect(home_team, "SMU") ~ "SMU",
      str_detect(home_team, "Stanford") ~ "Stanford",
      str_detect(home_team, "Syracuse") ~ "Syracuse",
      str_detect(home_team, "Virginia") ~ "Virginia",
      str_detect(home_team, "Wake Forest") ~ "Wake Forest"
    ),
    away_team = case_when(
      str_detect(away_team, "Virginia Tech") ~ "Virginia Tech",
      str_detect(away_team, "North Carolina") ~ "North Carolina",
      str_detect(away_team, "Notre Dame") ~ "Notre Dame",
      str_detect(away_team, "Boston College") ~ "Boston College",
      str_detect(away_team, "California") ~ "California",
      str_detect(away_team, "Clemson") ~ "Clemson",
      str_detect(away_team, "Duke") ~ "Duke",
      str_detect(away_team, "Florida State") ~ "Florida State",
      str_detect(away_team, "Georgia Tech") ~ "Georgia Tech",
      str_detect(away_team, "Louisville") ~ "Louisville",
      str_detect(away_team, "Miami") ~ "Miami (FL)",
      str_detect(away_team, "NC State") ~ "NC State",
      str_detect(away_team, "Pittsburgh") ~ "Pittsburgh",
      str_detect(away_team, "SMU") ~ "SMU",
      str_detect(away_team, "Stanford") ~ "Stanford",
      str_detect(away_team, "Syracuse") ~ "Syracuse",
      str_detect(away_team, "Virginia") ~ "Virginia",
      str_detect(away_team, "Wake Forest") ~ "Wake Forest"
    ),
    play_team = case_when(
      str_detect(play_team, "Virginia Tech") ~ "Virginia Tech",
      str_detect(play_team, "North Carolina") ~ "North Carolina",
      str_detect(play_team, "Notre Dame") ~ "Notre Dame",
      str_detect(play_team, "Boston College") ~ "Boston College",
      str_detect(play_team, "California") ~ "California",
      str_detect(play_team, "Clemson") ~ "Clemson",
      str_detect(play_team, "Duke") ~ "Duke",
      str_detect(play_team, "Florida State") ~ "Florida State",
      str_detect(play_team, "Georgia Tech") ~ "Georgia Tech",
      str_detect(play_team, "Louisville") ~ "Louisville",
      str_detect(play_team, "Miami") ~ "Miami (FL)",
      str_detect(play_team, "NC State") ~ "NC State",
      str_detect(play_team, "Pittsburgh") ~ "Pittsburgh",
      str_detect(play_team, "SMU") ~ "SMU",
      str_detect(play_team, "Stanford") ~ "Stanford",
      str_detect(play_team, "Syracuse") ~ "Syracuse",
      str_detect(play_team, "Virginia") ~ "Virginia",
      str_detect(play_team, "Wake Forest") ~ "Wake Forest"
    )
  )



# Define player_regex to include first names Like B.J. and Tre'Von

player_regex <- "^([A-Z]\\.)+[[:space:]]+[A-Z][a-zA-Z'’-]+|^[A-Z][a-zA-Z'’-]+[[:space:]]+[A-Z][a-zA-Z'’-]+"
```

```{r}
# create play_type variable from play_desc for score, foul, timeout, and sub
# extract player for each of those play types using str_extract and the pattern of the play-by-play

pbp_clean <- pbp |>
  mutate(
    play_type = if_else(str_detect(play_desc, "makes"), "score", NA_character_),
    play_type = if_else(str_detect(play_desc, "^Foul on"), "foul", play_type),
    play_type = if_else(str_detect(play_desc, "Timeout"), "team_timeout", play_type),
    play_type = if_else(str_detect(play_desc, "TV Timeout"), "tv_timeout", play_type),
    play_type = if_else(str_detect(play_desc, regex("subbing out|subbing in", ignore_case = TRUE)), "sub", play_type)
  ) |>
  filter(!play_type %in% c("jump ball", "block", "rebound", "tv timeout", "steal", "end")) |>
  filter(!str_detect(play_desc, regex("misses", ignore_case = TRUE))) %>%
  mutate(
    player = case_when(
      play_type == "score" ~ str_extract(play_desc, paste0("^", player_regex)),
      play_type == "foul"  ~ str_extract(play_desc, paste0("(?<=Foul on )", player_regex)),
      play_type == "sub" ~ str_extract(play_desc, paste0("^", player_regex)),
      TRUE ~ NA_character_
    )
  ) |>
  select(game_id, home_team, away_team, play_desc, play_type, player, play_team, home_score, away_score, half, secs_left_half, margin, close_game)

```

```{r}
# Create a points column for each event

pbp_clean <- pbp_clean |>
  mutate(points = case_when(
    str_detect(play_desc, regex("three point", ignore_case = TRUE)) ~ 3,
    str_detect(play_desc, regex("free throw", ignore_case = TRUE)) ~ 1,
    play_type == "score" ~ 2,
    TRUE ~ 0
  ))
```

```{r}
# counting fouls for each player and keep play_team

player_fouls <- pbp_clean |>
  filter(play_type == "foul") |>
  group_by(game_id, player, play_team) |>
  summarise(total_fouls = n(), .groups = "drop")
```

```{r}
# tracking timeouts

timeouts <- pbp_clean |>
  filter(play_type == "team_timeout") |>
  select(
    game_id,
    timeout_team = play_team,
    half,
    timeout_secs = secs_left_half
  )
```

```{r}
# tracking points scored by each player when the game is close

close_game_points <- pbp_clean %>%
  filter(abs(margin) <= 5 & play_type == "score") %>%
  group_by(game_id, player, play_team) %>%
  summarise(close_game_points = sum(points, na.rm = TRUE), .groups = "drop")
```

```{r}
# determines if the home or away team scores based on previous score (lag)
# rleid assigns a unique integer ID to each consecutive run of the same team by resetting every time the team changes

pbp_scores <- pbp_clean |>
  filter(play_type == "score") |>
  arrange(game_id, half, desc(secs_left_half)) |>
  group_by(game_id) |>
  mutate(scoring_team = play_team)|>
  mutate(run_increment = rleid(scoring_team),
         run_id = paste(game_id, run_increment, sep = "_")) |>
  ungroup() |>
  group_by(game_id, run_id, scoring_team) |>
  mutate(run_points = cumsum(points)) |>
  ungroup()
  
```

```{r}
# determine he number of points in each run and the length of the run

runs_summary <- pbp_scores |>
  group_by(game_id, half, run_id, scoring_team) |>
  summarise(
    run_points = max(run_points),        # total points in the run
    run_start_secs = first(secs_left_half),  # start of run
    run_end_secs = last(secs_left_half),     # end of run
    .groups = "drop"
  )
```

```{r}
# determines if there was a timeout called within 5 seconds of a run
# filters for timeouts called within 5 seconds of a run

runs_with_timeouts <- runs_summary |>
 left_join(timeouts, by = c("game_id", "half")) |>
  mutate(
    time_diff = abs(run_end_secs - timeout_secs),
    timeout_within_5 = time_diff <= 5
  ) |>
  filter(timeout_within_5)
```

```{r}
# for runs of 8+ points, determine if a timeout was called within 5 seconds of the end of the run

big_runs_summary <- runs_summary |>
  filter(run_points >= 8) |>
  select(game_id, run_id, scoring_team, run_points, run_start_secs, run_end_secs, half) |>
  left_join(timeouts, by = c("game_id", "half")) |>
  mutate(
    time_after_run = run_end_secs - timeout_secs,  # Positive means timeout came after run ended
    quick_timeout_check = (time_after_run >= 0 & time_after_run <= 5)
  ) |>
  group_by(game_id, run_id) |>
  summarise(
    scoring_team = first(scoring_team),
    run_points = first(run_points),
    run_start_secs = first(run_start_secs),
    run_end_secs = first(run_end_secs),
    half = first(half),
    quick_timeout = any(quick_timeout_check, na.rm = TRUE),
    timeout_team = first(timeout_team[quick_timeout_check], default = NA_character_),
    .groups = "drop"
  )

```
```{r}
runs_against <- runs_summary |>
  filter(run_points >= 8) |>
  left_join(pbp_clean |> distinct(game_id, home_team, away_team), by = "game_id") |>
  mutate(opponent_team = if_else(scoring_team == home_team, away_team, home_team)) |>
  count(opponent_team, name = "total_8plus_runs_against")
```

```{r}
# create a table showing:
# number of any type of run against team
# number of timeouts taken within 5 seconds of any run
# percentage of timeouts in response to a run
# number of 8+ pt runs against team
# number of timeouts taken within 5 seconds of 8+ pt run
# percentage of timeouts in response to 8+ pt run

defensive_summary <- big_runs_summary |>
  filter(!is.na(timeout_team)) |>
  group_by(timeout_team) |>
  summarise(quick_timeouts_called = n_distinct(run_id)) |>  # Count unique runs, not total timeouts
  left_join(runs_against, by = c("timeout_team" = "opponent_team")) |>
  mutate(timeout_pct = round(quick_timeouts_called / total_8plus_runs_against * 100, 1)) |>
  arrange(desc(timeout_pct))
```

```{r}
# counts the number of unique runs each team scored over the course of the season and the average number of run points

runs_by_team <- pbp_scores |>
  filter(run_points >= 8) |>
  group_by(scoring_team) |>
  summarise(
    n_runs = n_distinct(run_id),
    avg_run_points = mean(run_points)
  ) |>
  arrange(desc(n_runs))
```

```{r}
# Checking that teams omitted from the defensive summary had 0 quick timeouts called after an 8+ run against them

runs_against |>
  left_join(
    defensive_summary |> select(timeout_team, quick_timeouts_called),
    by = c("opponent_team" = "timeout_team")
  ) |>
  mutate(quick_timeouts_called = replace_na(quick_timeouts_called, 0)) |>
  arrange(desc(total_8plus_runs_against))
```











