---
title: "UNC-Duke Analysis (1986-2025)"
output: html_notebook
---

Statistics by venue are limited to 2005-2025 due to lack of game data tracked prior to 2005. Games prior to 2005 only have total points recorded.

## Data Cleaning

```{r}
unc_duke <- read_csv("UNC-Duke Statistics 1986-2025 - Sheet1.csv")
```

```{r}
# All numerics are coded as characters

str(unc_duke)
```

```{r}
unc_duke <- unc_duke |>
  mutate(
    UNC_FT_pct = as.numeric(UNC_FT_pct),
    Duke_FT_pct = as.numeric(Duke_FT_pct)
  )
```

```{r}
header_row <- unc_duke[1, ]
```

```{r}
# View the variable names

names(unc_duke)
```

```{r}
names(unc_duke) <- ifelse(
  grepl("^Team", names(unc_duke)),  #if the name starts with "Team"
  paste0("UNC_", as.character(header_row[1, ])), #replace with "UNC_TextFromHeaderRow"
  names(unc_duke) #otherwise leave it the same
)
```

```{r}
names(unc_duke) <- ifelse(
  grepl("^Opponent", names(unc_duke)),  #if the name starts with "Opponent"
  paste0("Duke_", as.character(header_row[1, ])), #replace with "Duke_TextFromHeaderRow"
  names(unc_duke) #otherwise leave it the same
)
```

```{r}
# Replace generic variable names in first 7 columns with data from the header_row

names(unc_duke)[1:7] <- as.character(header_row[1, 1:7])
```

```{r}
# Drop the first row of data after variable names have been fixed

unc_duke <- unc_duke[-1, ]
```

```{r}
# Globally substitute the sort icon with nothing (remove it)

names(unc_duke) <- gsub("▼", "", names(unc_duke))
```

```{r}
# Removing the "NCAA" after the date

unc_duke <- unc_duke |>
  mutate(Date = gsub(" NCAA", "", Date))
```

```{r}
# Rename venues

unc_duke <- unc_duke |>
  mutate(
    Venue = case_when(
      grepl("@", Venue) ~ "Cameron Indoor",  
      is.na(Venue) ~ "Smith Center",          
      Venue == "N" ~ "Neutral",        
      TRUE ~ Venue                     
    )
  )
```

```{r}
# Create variables for Win_Loss, UNC_PTS, and Duke_PTS from original Result column

unc_duke <- unc_duke |>
  mutate(
    Win_Loss = substr(Result, 1, 1), #take the first character in Result
    score_text = str_trim(substr(Result, 3, nchar(Result))) #take everything from the 3rd character (start of score) onwards
  ) |>
  separate(score_text, into = c("UNC_PTS", "Duke_PTS"), sep = "-", convert = TRUE) |> #split the score at the hyphen
  select(-Result) #remove original Result variable
```

```{r}
# Convert % to _pct for later data manipulation

names(unc_duke) <- gsub("%", "_pct", names(unc_duke))
```

```{r}
# Create a variable for season

unc_duke <- unc_duke |>
  mutate(
    Season = case_when(
      month(Date) >= 11 ~ paste0(year(Date), "-", year(Date) + 1),
      TRUE ~ paste0(year(Date) - 1, "-", year(Date))
    )
  )
```

```{r}
colnames(unc_duke)
```


```{r}
# Convert all numeric variables

unc_duke <- unc_duke |>
  mutate(
    Date = as.Date(Date),
    across(7:31, as.numeric),
    across(33:34, as.numeric)
  )
```

```{r}
# Filter for results with detailed statistics

unc_duke_0405_2425 <- unc_duke |>
  filter(year(Date) > 2004)
```

## Data Visualization

```{r}
# Create a variable for free throw percentage margin

unc_duke_0405_2425 <- unc_duke_0405_2425 |>
  mutate(FT_pct_margin = UNC_FT_pct - Duke_FT_pct)

```


```{r}
# Pivot table longer in preparation for making a time-series plot

ft_pct_long <- unc_duke_0405_2425 %>%
  select(Date, Venue, UNC_FT_pct, Duke_FT_pct) %>%
  pivot_longer(cols = c(UNC_FT_pct, Duke_FT_pct),
               names_to = "Team",
               values_to = "FT_pct")
```

```{r} 
# Removing neutral site for visualizations

ft_pct_long_noNeutral <- ft_pct_long |>
  filter(Venue %in% c("Smith Center", "Cameron Indoor"))
```

```{r}
# calculating median free throw percentage by team by venue
# they are extremely similar so I will not plot this trend line

venue_trends <- ft_pct_long_noNeutral |>
  group_by(Venue, Team) |>
  summarise(median_FT = median(FT_pct, na.rm = TRUE), .groups = "drop")
```

```{r}
ggplot(ft_pct_long_noNeutral, aes(x = Date, y = FT_pct, color = Venue)) +
  geom_line(aes(group = interaction(Team, Venue)), alpha = 0.7, size = 0.5) +  # one line per Team x Venue
  geom_point(alpha = 0.7, size = 1) +
  scale_color_manual(values = c("Smith Center" = "#4B9CD3", "Cameron Indoor" = "#00539B")) + #using official hex colors for schools
  scale_x_date(date_labels = "%Y", date_breaks = "2 years") + #clean up the x-axis by only using every other year
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + #rotate x-axis labels
  facet_wrap(
    ~Team,
    labeller = labeller(Team = c( #rename the facets
      "Duke_FT_pct" = "Duke",
      "UNC_FT_pct" = "UNC")
      )
    )+
  labs(
    title = "UNC vs Duke Free Throw % per Game",
    x = "Date",
    y = "Free Throw %",
    color = "Venue"
  )
  
```
```{r}
ggsave("ft_pct_plot.png", width = 16, height = 6)
```

