---
title: "2025-2026 ACC Conference Stats"
output: html_notebook
---

```{r}
acc_stats2526 <- read.csv("/Users/hanabaskin/Desktop/ACC Basketball 25-26 - Sheet1.csv")
```

```{r}
head(acc_stats2526)
```
```{r}
colSums(is.na(acc_stats2526))
```
```{r}
install.packages("rvest")
library(rvest)
install.packages("janitor")
library(janitor)
install.packages("stringr")
library(stringr)
install.packages("dplyr")
library(dplyr)
```
```{r}
url <- "https://www.sports-reference.com/cbb/conferences/acc/men/2026-stats.html"
acc_page2526 <- read_html(url)
```

```{r}
acc_basketball_confstats_2526 <- acc_page2526 |>
  html_element("#players_per_game_conf") |>
  html_table() |>
  clean_names()

acc_basketball_confstats_2526
```

```{r}
top_scoring_concentration_team <- acc_basketball_confstats_2526 |>
 group_by(team) |>
  mutate(percent_total_team_points = pts / sum(pts) * 100) |>
  summarise(top_score_share = max(percent_total_team_points)) |>
  arrange(desc(top_score_share))
```
```{r}
View(top_scoring_concentration_team)
```
```{r}
top_score_share_player <- acc_basketball_confstats_2526 |>
 group_by(team) |>
  mutate(percent_total_team_points = pts / sum(pts) * 100) |>
  slice_max(percent_total_team_points, n = 1) |>
  select(team, player, percent_total_team_points) |>
  arrange(desc(percent_total_team_points))
```
```{r}
View(top_score_share_player)
```
```{r}
top2_score_share_player <- acc_basketball_confstats_2526 |>
 group_by(team) |>
  mutate(percent_total_team_points = pts / sum(pts) * 100,
         team_top_score = max(percent_total_team_points)
         ) |>
  slice_max(percent_total_team_points, n = 2) |>
  arrange(desc(team_top_score), desc(percent_total_team_points)) |>
  select(team, player, percent_total_team_points)
```
```{r}
View(top2_score_share_player)
```
```{r}
View(top2_score_share_player |>
  group_by(team) |>
  summarise(
    percent_sum = sum(percent_total_team_points)
  ) |>
  arrange(desc(percent_sum)))
```

